### ISSUE TITLE
Fails on startup due to missing source file

### ISSUE THREAD

**Issue by sronsiek** [chuyskywalker/nomad-ui#1]
I tried building the docker-image from source as well as pulling from docker-hub.

On running the image & pointing a browser at the listening port, the following msg is displayed in the browser:

```
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 3

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/index.php on line 3
```

Within the image, /var/www/htmp/index.php requires autoload.php, yet a find across the entire file system shows this file is not present.

Possibly not related, but I see these messages during the build process:

```
Get:1 http://httpredir.debian.org/debian/ jessie/main libsodium13 amd64 1.0.0-1 [138 kB]
Get:2 http://httpredir.debian.org/debian/ jessie/main libsodium-dev amd64 1.0.0-1 [146 kB]
debconf: delaying package configuration, since apt-utils is not installed

```

and at the end:

```
Build process completed successfully
Installing '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/libsodium.so'
install ok: channel://pecl.php.net/libsodium-1.0.6
configuration option "php_ini" is not set to php.ini location
You should add "extension=libsodium.so" to php.ini
```

Run string:

```
docker run -ti --rm --name=chuyskywalker_nomad-ui -p 8090:80 \
   -e 'NOMAD_BASEURL=http://nomad.service.consul:4646' \
   chuyskywalker/nomad-ui
```

**Comment by sronsiek** [comment]
Ok, I got it running in dev mode. It seems the step that runs composer generates autoload files. So I guess this step needs adding to the Dockerfile?

Also, the instructions to run in dev mode are missing the internal-to-external port-mapping arg.

**Comment by chuyskywalker** [comment]
In the dev instructions, this line:

```
docker run -ti --rm -v $(pwd)/html:/app composer/composer install
```

should have installed the autoload.php.

The pushed version ought to have it as well, let me see...huh, it was missing.

Fixed and pushed a new version:

```
# docker pull chuyskywalker/nomad-ui
Using default tag: latest
latest: Pulling from chuyskywalker/nomad-ui
Digest: sha256:8089cc513e34e9e30a164475c49f4b86e4dc48d46a846414ee65890959f092a7
Status: Image is up to date for chuyskywalker/nomad-ui:latest
# docker run -ti --rm chuyskywalker/nomad-ui ls -alh vendor
```

I don't auto-build the image right now; not sure how I built a version without the composer deps installed. I'll add the composer step to the full `dockerfile` since it ought to be there anywho.

**Comment by chuyskywalker** [comment]
Thanks for taking the time to report this and #2, I've fixed both and pushed a new `latest` image up to dockerhub.
