### ISSUE TITLE
Fatal on node selection

### ISSUE THREAD

**Issue by sronsiek** [chuyskywalker/nomad-ui#2]
Running in dev mode (see Issue#1), I encounter a Fatal when clicking any node link in the ID column of  the Nodes page. Possibly my nomad cfg is not right, but the ui should be robust enough to handle this.

```
Fatal error: Uncaught Twig_Error_Runtime: Impossible to access an attribute ("CPU") on a null variable in "node.html.twig" at line 134 in /var/www/html/vendor/twig/twig/lib/Twig/Template.php:509 Stack trace: 
#0 /tmp/4a/4aed4dcf9789e290dfb461e8af1d76faad03f9818b33336804ae7295cb3be12c.php(296): Twig_Template->getAttribute(NULL, 'CPU', Array) 
#1 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_049743a08e6d632c4b9fe41a7ddf0353c7753f090d29edad3725b0f6c1d9f26a->block_content(Array, Array) 
#2 /tmp/3e/3ea6b00da3d96e8645cbbeae7188609f9e868f21d6c0e0011623c75fb19fbfbe.php(62): Twig_Template->displayBlock('content', Array, Array) 
#3 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_0cf12f6ca464885e9b281bc17d84e293629fd2f1572866672aee49959a7e2d55->doDisplay(Array, Array) 
#4 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#5 /tmp/4a/4aed4dcf9789e290dfb461e8af1d76faad03f9818b33336804ae7295cb3be12c.php(25): Twig_Template->dis in /var/www/html/vendor/twig/twig/lib/Twig/Template.php on line 509
```

**Comment by chuyskywalker** [comment]
I'd be interested to see why your instance doesn't have CPU statistics.

If you turn off [this strict line](https://github.com/chuyskywalker/nomad-ui/blob/master/html/src/Nomad.php#L16) I believe the page should render. Then, if you could post your JSON from the `Stats` tab at the bottom, I could see why there are no CPU stats.

**Comment by chuyskywalker** [comment]
BTW, the reason I think this is failing is that I think the `node/stats` api call is new to Nomad 0.4, which is what I'm testing against.

**Comment by sronsiek** [comment]
We are at an early stage of setting up a consul+registrator+nomad cluster - we know there are cfg issues which is the likely cause of lack of CPU data, I can't be more precise at this time. Nomad version = 0.4.1.

Hopefully we'll get a chance to test yr fix soon ... then I'll provide some feedback.
